#!/usr/bin/env node
import * as request from 'request';
import * as formData from 'form-data';
import * as program from 'commander';

let targetUrl: string;
program
.version(`v${require('../package.json').version}`)
.description('A tool to auto generate data in discourse')
.option('--username [value]', 'Api user name')
.option('--apikey [value]', 'Api key')
.option('--title [value]', 'title of a topic.', 'Topic from data generator')
.option('--content [value]', 'content of a topic.', 'This message is autogenerated.')
.arguments('<targetSite>')
.action(function (targetSite: string) {
    targetUrl = targetSite;
 })
.parse(process.argv);

if (!targetUrl || !program.username || !program.apikey) {
    console.log('Error: must specify target_site, api_username and api_key');
    program.help();
}

let data = {
    api_key: program.apikey,
    api_username: program.username,
    title: program.title,
    raw: program.content
};

request.post({
    url: `http://${targetUrl}/posts`,
    formData: data
}, (err, httpResponse, body) => {
    if (err) {
        return console.error('upload failed:', err);
    }
    console.log('Upload successful!  Server responded with:', body);
});
