#!/usr/bin/env node
import * as request from 'request';
import * as program from 'commander';
let threadSleep = require('thread-sleep');
let discourse = require('discourse-sdk');

let targetUrl: string;
program
.version(`v${require('../package.json').version}`)
.description('A tool to auto generate data in discourse')
.option('--username [value]', 'Api user name')
.option('--apikey [value]', 'Api key')
.option('--title [value]', 'title of a topic.', 'Topic from data generator')
.option('--content [value]', 'content of a topic.', 'This message is autogenerated.')
.option('--count [value]', 'how many time it runs.')
.arguments('<targetSite>')
.action(function (targetSite: string) {
    targetUrl = targetSite;
 })
.parse(process.argv);

if (!targetUrl || !program.username || !program.apikey) {
    console.log('Error: must specify target_site, api_username and api_key');
    program.help();
}

let count = 1;
if (program.count) {
    try {
        count = parseInt(program.count, 10);
    } catch (e) {}
}

let data = {
    api_key: program.apikey,
    api_username: program.username,
    title: program.title,
    raw: program.content
};

if (!(targetUrl.indexOf('http') === 0)) {
    targetUrl = `http://${targetUrl}`;
}

let client = new discourse(targetUrl, program.apikey, program.username);

let title: string = program.title;

fireRequest(client, data, title, count);

function sleep(): void {
    let sleepSeconds = 60;
    console.log(`Sleep for ${sleepSeconds} seconds.`);
    threadSleep(sleepSeconds * 1000);
}

function fireRequest(client: any, data: any, title: string, count: number): void {
    if (count > 1) {
        data.title = `${title} ${count}`;
    } else {
        data.title = title;
    }
    try {
        client.createTopic(data.title, data.raw, 0, (err: any, body: any, code: any) => {
            if (err) {
                console.error(`{count}: Upload failed: ${err}`);
            }
            try {
                body = JSON.parse(body);
                if (!body.errors) {
                    console.log(`{count}: Upload successful!`);
                } else {
                    console.error(`{count}: Upload failed: ${body.errors}`);
                    if (body.errors[0] && body.errors[0].toString().indexOf('daily limit') >= 0) {
                        throw 'reach api limit';
                    }
                }

                if (count > 1) {
                    fireRequest(client, data, title, count - 1);
                }
            } catch (e) {
                console.log(`Error happen: ${e}`);
                sleep();
                fireRequest(client, data, title, count);
            }
        });
    } catch (e) {
        console.log(`Error happen: ${e}`);
        sleep();
        fireRequest(client, data, title, count);
    }
}
